<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: kychris
 * Date: Sat, 02 Dec 2017 10:23:07 +0000
 */

$conf['title'] = 'Coding Base';
$conf['start'] = 'sidebar';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
